name: CoreX
version: 1.0
author: XECortex
main: org.ddnss.xecortex.corex.Main
load: POSTWORLD
api-version: 1.16
softdepend: [PlaceholderAPI, HolographicDisplays, ProtocolLib]
permissions:
  corex.chat.allow-colors:
    description: "Allow the player to use color codes in the chat"
    default: op
  corex.chat.highlight-urls:
    description: "Detect and highlight URLs that the player sends into the chat"
    default: op