################################################################
# +----------------------------------------------------------+ #
# |                   CoreX Configuration                    | #
# +----------------------------------------------------------+ #
################################################################
#
# This plugin was created by CORTƎX#4212 for Spigot/Bukkit 1.16
# Do not steal my code or I'll eat your muffins.
# Yes, the chocolate ones!


################################
#            Plugin            #
################################

# DO NOT CHANGE THIS!
version: 0.4

# Select language for messages
# Available languages: en, de
locale: "en"


################################
#             Chat             #
################################

chat:
  # Toggle if players can use color codes or the PlaceholderAPI in the chat
  allow-colors: true
  placeholder-support: false
  # You can set a pattern to format the chat here
  # Use %player% for the player's display name and %message%
  format-chat: true
  format: "%player% &7» &r%message%"
  # If you want to use placeholders in your chat formatting, enable this
  format-placeholder-support: false


################################
#           Messages           #
################################

# Custom join- and quit-message
join-message:
  enable: true
  message: "&r%player_displayname% &7joined the Server"

quit-message:
  enable: true
  message: "&r%player_displayname% &7left the Server"

# Custom message of the day (MOTD)
motd:
  enable: true
  message:
    line1: "               &8----[ &a< WELCOME > &8]----"
    line2: "          &7Feel free to join our nice server!"

join-motd:
  enable: true
  message: "&7Welcome, &r%player_displayname%&7!\n&r%server_online% &7players online.\n&7You are in &r%player_world%&7, it's &r%player_world_time_24%&7.\n&7Your position: &r%player_x%, %player_y%, %player_z%"


################################
#           Spawning           #
################################

# Teleport players back to the spawn on join
spawn-on-join:
  enable: true
  # Enter the spawn world name here. Leave empty to select the world the player is actually in
  world: ""

# Change respawn behavior
respawn:
  # Respawn mode: select if players should respawn in their bed or on the world spawn point
  respawn-in-bed: true
  # Enter the spawn world name here. "respawn-in-bed" needs to be false. Leave empty to select the world the player is actually in
  world: ""


################################
#           Sleeping           #
################################

# Better sleep experience for players
# Set how many players have to sleep to skip the night
sleeping:
  # Sleep mode:
  # Possible values are "percentage", "absolute" or "all"
  mode: "percentage"
  # The function of this value depends of the selected sleep mode.
  # If your sleep mode is "percentage", this defines what percentage of the players has to sleep.
  # In "absolute" mode, you select how many players have to sleep, independent of how many players are online
  # With sleep mode "all", this value is ignored
  needed: 20
  # The time in ticks players have to sleep
  time: 100


################################
#          Nicknames           #
################################

nicknames:
  maxlength: 32
# TODO: add /nick
